name: BITNATION
favicon: null
layout_spectrum: 0.95615
typography_spectrum: 0.54252
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130b0a'
    - '#634632'
    - '#f4ddea'
    - '#c49b8d'
    - '#aa683d'
  brandStrength: 0.5
  lightness: 0.8471207127440721
  saturation: 0.22968310839496553
  rhythmicContrast: 0.09283030754886568
purpose: []
