name: BITNATION
favicon: null
layout_spectrum: 0.73385
typography_spectrum: 0.54252
title: Bitnation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011735'
    - '#243f53'
    - '#b8988d'
    - '#dcccc9'
    - '#924632'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
