name: Bitnation Magazine
favicon: null
layout_spectrum: 0.76471
typography_spectrum: 0.75274
title: Bitnation Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6743d'
    - '#2b1400'
    - '#783905'
    - '#ffd3ae'
    - '#fffcfa'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
